name: geoaugment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - rasterio
  - gdal
  - pyproj
  - shapely
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - pyyaml
  - click
  - tqdm
  - pip
  - pip:
      - torchgeo
